import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("package keeps legacy ui and adds separate next scripts", async () => {
  const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));

  assert.equal(pkg.scripts.ui, "node scripts/server.js");
  assert.equal(pkg.scripts["dev:next"], "next dev -H 127.0.0.1");
  assert.equal(pkg.scripts["build:next"], "next build");
  assert.equal(pkg.scripts["start:next"], "next start -H 127.0.0.1");
  assert.ok(pkg.dependencies.next);
  assert.ok(pkg.dependencies.react);
  assert.ok(pkg.dependencies["react-dom"]);
});

test("next app shell files exist", async () => {
  const layout = await readFile(new URL("../src/app/layout.tsx", import.meta.url), "utf8");
  const page = await readFile(new URL("../src/app/page.tsx", import.meta.url), "utf8");
  const appShell = await readFile(new URL("../src/components/app-shell.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../src/app/globals.css", import.meta.url), "utf8");

  assert.match(layout, /import "\.\/globals\.css"/);
  assert.match(layout, /AppShell/);
  assert.match(page, /工作台/);
  assert.match(page, /href="\/settings"/);
  assert.match(page, /href="\/noon-workbench"/);
  assert.match(appShell, /Noon Tools/);
  assert.match(appShell, /1688 采集/);
  assert.match(appShell, /商品仓库/);
  assert.match(appShell, /Noon 工作台/);
  assert.match(appShell, /店铺/);
  assert.match(appShell, /配置/);
  assert.match(appShell, /pathname === "\/noon-workbench"/);
  assert.match(appShell, /noon-legacy-shell/);
  assert.match(css, /--font-ui/);
  assert.match(css, /\.rail/);
  assert.match(css, /\.noon-legacy-shell/);
  assert.match(css, /--color-panel: #0e1320/);
  assert.doesNotMatch(css, /\.noon-workbench-page[\s\S]*--color-panel: #ffffff/);
  assert.match(css, /\.nav a\.active/);
});

test("next settings route and page use shared settings module", async () => {
  const route = await readFile(new URL("../src/app/api/settings/route.ts", import.meta.url), "utf8");
  const page = await readFile(new URL("../src/app/settings/page.tsx", import.meta.url), "utf8");
  const form = await readFile(new URL("../src/app/settings/settings-form.tsx", import.meta.url), "utf8");

  assert.match(route, /readUiSettings/);
  assert.match(route, /saveUiSettings/);
  assert.match(route, /export async function GET/);
  assert.match(route, /export async function POST/);
  assert.match(page, /SettingsForm/);
  assert.match(form, /"use client"/);
  assert.match(form, /fetch\("\/api\/settings"\)/);
  assert.match(form, /method: "POST"/);
});

test("settings client form does not import server filesystem module values", async () => {
  const form = await readFile(new URL("../src/app/settings/settings-form.tsx", import.meta.url), "utf8");

  assert.doesNotMatch(form, /import\s+\{[^}]*UI_SETTING_KEYS[^}]*\}\s+from\s+["']@\/lib\/settings["']/);
});

test("next settings form uses field-appropriate controls", async () => {
  const form = await readFile(new URL("../src/app/settings/settings-form.tsx", import.meta.url), "utf8");

  assert.match(form, /settings-layout/);
  assert.match(form, /settings-stack/);
  assert.match(form, /setting-hint/);
  assert.match(form, /控制 1688 采集浏览器和网络代理/);
  assert.match(form, /控制 Noon 自动化使用的浏览器内核/);
  assert.match(form, /用于利润计算和 AI 文案生成/);
  assert.match(form, /type:\s*"select"/);
  assert.match(form, /type:\s*"checkbox"/);
  assert.match(form, /const browserModeOptions = \[[\s\S]*显示窗口[\s\S]*后台运行[\s\S]*\]/);
  assert.match(form, /name:\s*"headless"[\s\S]*type:\s*"select"[\s\S]*options:\s*browserModeOptions/);
  assert.match(form, /name:\s*"noonBrowser"[\s\S]*系统 Chrome[\s\S]*CloakBrowser/);
  assert.match(form, /name:\s*"noonCloakTyping"[\s\S]*type:\s*"checkbox"/);
  assert.match(form, /name:\s*"noonHeadless"[\s\S]*type:\s*"select"[\s\S]*options:\s*browserModeOptions/);
  assert.match(form, /name:\s*"globalExchangeRate"/);
  assert.match(form, /name:\s*"globalPlatformFeeRate"/);
  assert.match(form, /name:\s*"globalTargetMargin"/);
  assert.match(form, /name:\s*"deepSeekModel"[\s\S]*deepseek-v4-flash[\s\S]*deepseek-v4-pro/);
  assert.match(form, /name:\s*"deepSeekApiKey"[\s\S]*type:\s*"password"/);
  assert.match(form, /<select/);
  assert.match(form, /<input[\s\S]*type="checkbox"/);
  assert.match(form, /<input[\s\S]*type=\{field\.type \|\| "text"\}/);
  assert.match(form, /payload\[field\.name\] = formData\.get\(field\.name\) === "on" \? "true" : "false"/);
  assert.doesNotMatch(form, /uploadHeadless|deepseekModel|deepseekApiKey|ocrProvider|ocrLanguage/);
});

test("next repositories module has routes and list workspace", async () => {
  const home = await readFile(new URL("../src/app/page.tsx", import.meta.url), "utf8");
  const repositoriesPage = await readFile(new URL("../src/app/repositories/page.tsx", import.meta.url), "utf8");
  const workspace = await readFile(new URL("../src/app/repositories/repositories-workspace.tsx", import.meta.url), "utf8");
  const noonWorkbenchPage = await readFile(new URL("../src/app/noon-workbench/page.tsx", import.meta.url), "utf8");
  const noonWorkbenchWorkspace = await readFile(new URL("../src/app/noon-workbench/noon-workbench-workspace.tsx", import.meta.url), "utf8");
  const detailPage = await readFile(new URL("../src/app/product-detail/[...path]/page.tsx", import.meta.url), "utf8");
  const repositoriesRoute = await readFile(new URL("../src/app/api/repositories/route.ts", import.meta.url), "utf8");
  const productsRoute = await readFile(new URL("../src/app/api/products/route.ts", import.meta.url), "utf8");
  const uploadJobsRoute = await readFile(new URL("../src/app/api/upload-jobs/route.ts", import.meta.url), "utf8");
  const uploadJobRoute = await readFile(new URL("../src/app/api/upload-jobs/[id]/route.ts", import.meta.url), "utf8");
  const uploadCancelRoute = await readFile(new URL("../src/app/api/upload-jobs/[id]/cancel/route.ts", import.meta.url), "utf8");
  const catalogSyncRoute = await readFile(new URL("../src/app/api/noon-catalog-sync-jobs/route.ts", import.meta.url), "utf8");
  const catalogSnapshotRoute = await readFile(new URL("../src/app/api/noon-catalog-sync/route.ts", import.meta.url), "utf8");
  const bulkOperationsRoute = await readFile(new URL("../src/app/api/noon-bulk-operations/route.ts", import.meta.url), "utf8");
  const bulkUpdatesRoute = await readFile(new URL("../src/app/api/noon-bulk-updates/route.ts", import.meta.url), "utf8");
  const bulkUpdateFilesRoute = await readFile(new URL("../src/app/api/noon-bulk-updates/files/[...path]/route.ts", import.meta.url), "utf8");
  const productsLib = await readFile(new URL("../src/lib/products.ts", import.meta.url), "utf8");
  const jobsLib = await readFile(new URL("../src/lib/jobs.ts", import.meta.url), "utf8");
  const css = await readFile(new URL("../src/app/globals.css", import.meta.url), "utf8");

  assert.match(home, /href="\/repositories"/);
  assert.match(repositoriesPage, /RepositoriesWorkspace/);
  assert.match(workspace, /"use client"/);
  assert.match(workspace, /fetch\("\/api\/repositories/);
  assert.match(workspace, /fetch\(`\/api\/products\?\$\{params\}`\)/);
  assert.match(workspace, /仓库数据源/);
  assert.match(workspace, /搜索/);
  assert.match(workspace, /import \{ Pager \} from "@\/components\/workbench\/pager"/);
  assert.match(workspace, /<Pager/);
  assert.match(workspace, /repository-summary-card/);
  assert.match(workspace, /product-source-card/);
  assert.match(workspace, /product-search-card/);
  assert.match(workspace, /repository-controls repository-toolbar product-bulk-bar/);
  assert.match(workspace, /repository-table-head/);
  assert.match(workspace, /product-title-button/);
  assert.match(workspace, /物流信息/);
  assert.match(workspace, /海关编码\(HS Code\)/);
  assert.match(workspace, /采集时间/);
  assert.match(workspace, /操作/);
  assert.match(workspace, /1688 ID/);
  assert.match(workspace, /已创建草稿/);
  assert.match(workspace, /原始链接/);
  assert.match(workspace, /已调整/);
  assert.match(workspace, /product-health-dot/);
  assert.match(workspace, /product-price/);
  assert.match(workspace, /product-sku/);
  assert.match(workspace, /productLogisticsText/);
  assert.match(workspace, /productHsCode/);
  assert.match(workspace, /productCollectedAt/);
  assert.match(workspace, /formatUploadStatus/);
  assert.match(workspace, /product-detail/);
  assert.match(workspace, /uploadStoreId/);
  assert.match(workspace, /selectPageProducts/);
  assert.match(workspace, /selectedProductDirs/);
  assert.match(workspace, /uploadAllButton/);
  assert.match(workspace, /uploadSelectedButton/);
  assert.match(workspace, /productDirs:\s*selectedProductDirs/);
  assert.match(workspace, /totalItems=\{pagination\.totalItems\}/);
  assert.match(workspace, /totalPages=\{pagination\.totalPages\}/);
  assert.match(workspace, /fetch\("\/api\/upload-jobs"/);
  assert.match(workspace, /uploadProgress/);
  assert.match(workspace, /data-upload-progress/);
  assert.match(workspace, /fetch\(`\/api\/upload-jobs\/\$\{uploadJobId\}`\)/);
  assert.match(workspace, /parseUploadJobProgress/);
  assert.doesNotMatch(workspace, /window\.location\.href = `\/upload-jobs/);
  assert.doesNotMatch(workspace, /fetch\("\/api\/noon-catalog-sync-jobs"/);
  assert.match(workspace, /mode = "upload"/);
  assert.match(noonWorkbenchWorkspace, /Noon 工作台/);
  assert.match(noonWorkbenchPage, /NoonWorkbenchWorkspace/);
  assert.doesNotMatch(noonWorkbenchPage, /RepositoriesWorkspace/);
  assert.doesNotMatch(noonWorkbenchPage, /mode="operations"/);
  assert.match(noonWorkbenchWorkspace, /noon-catalog-hero/);
  assert.match(noonWorkbenchWorkspace, /商品目录/);
  assert.match(noonWorkbenchWorkspace, /FBN\/FBP 模式/);
  assert.match(noonWorkbenchWorkspace, /Global \(NGS\) 模式/);
  assert.match(noonWorkbenchWorkspace, /首次使用请先同步 SKU 数据/);
  assert.match(noonWorkbenchWorkspace, />API 快速同步</);
  assert.match(noonWorkbenchWorkspace, /导出同步/);
  assert.match(noonWorkbenchWorkspace, /type CatalogSyncSource = "internal_api" \| "export"/);
  assert.match(noonWorkbenchWorkspace, /onStart\("internal_api"\)/);
  assert.match(noonWorkbenchWorkspace, /onStart\("export"\)/);
  assert.match(noonWorkbenchWorkspace, /title=\{catalogMode === "global" \? undefined : "导出同步仅支持 Global 模式"\}/);
  assert.equal(noonWorkbenchWorkspace.match(/<CatalogSyncActions/g)?.length, 2);
  assert.equal(noonWorkbenchWorkspace.match(/function CatalogSyncActions\(/g)?.length, 1);
  assert.match(noonWorkbenchWorkspace, /function CatalogSyncActions\([\s\S]*API 快速同步[\s\S]*导出同步/);
  const catalogSyncActions = noonWorkbenchWorkspace.match(/function CatalogSyncActions\([\s\S]*?\n}\n\nexport default/)?.[0] || "";
  assert.doesNotMatch(catalogSyncActions, /className="secondary"/);
  assert.match(noonWorkbenchWorkspace, /const catalogSyncDisabled = syncStatus === "running" \|\| !storeId/);
  assert.equal(noonWorkbenchWorkspace.match(/disabled=\{catalogSyncDisabled\}/g)?.length, 2);
  assert.equal(noonWorkbenchWorkspace.match(/disabled=\{exportDisabled\}/g)?.length, 1);
  assert.match(noonWorkbenchWorkspace, /aria-describedby=\{catalogMode === "global" \? undefined : "catalog-export-mode-note"\}/);
  assert.match(noonWorkbenchWorkspace, /id="catalog-export-mode-note"/);
  assert.match(noonWorkbenchWorkspace, /JSON\.stringify\(\{ storeId, mode: catalogMode, source \}\)/);
  assert.match(noonWorkbenchWorkspace, /async function startCatalogSync\(source: CatalogSyncSource\) \{[\s\S]*?try \{[\s\S]*?fetch\("\/api\/noon-catalog-sync-jobs"[\s\S]*?await response\.json\(\)[\s\S]*?\} catch \(error\) \{[\s\S]*?setSyncStatus\("failed"\)[\s\S]*?error instanceof Error \? error\.message : "同步 SKU 任务创建失败。"[\s\S]*?setStatus\("同步 SKU 失败"\)/);
  assert.match(noonWorkbenchWorkspace, /正在读取 API 第/);
  assert.match(noonWorkbenchWorkspace, /currentPage \/ totalPages/);
  assert.doesNotMatch(noonWorkbenchWorkspace, />重新同步</);
  assert.match(noonWorkbenchWorkspace, /selectedRowKeys/);
  assert.match(noonWorkbenchWorkspace, /toggleAllRows/);
  assert.match(noonWorkbenchWorkspace, /toggleRow/);
  assert.match(noonWorkbenchWorkspace, /applyBulkOperation/);
  assert.match(noonWorkbenchWorkspace, /fetch\("\/api\/noon-bulk-operations"/);
  assert.match(noonWorkbenchWorkspace, /storeId/);
  assert.match(noonWorkbenchWorkspace, /exportGlobalBulkUpdates/);
  assert.match(noonWorkbenchWorkspace, /已选择 \{selectedCount\} 个商品/);
  assert.match(noonWorkbenchWorkspace, /批量改商品属性/);
  assert.match(noonWorkbenchWorkspace, /批量调价/);
  assert.match(noonWorkbenchWorkspace, /批量改FBP\/NGS库存/);
  assert.match(noonWorkbenchWorkspace, /批量改时效/);
  assert.match(noonWorkbenchWorkspace, /导出 Global 表/);
  assert.match(noonWorkbenchWorkspace, /取消选择/);
  assert.match(noonWorkbenchWorkspace, /批量删除/);
  assert.doesNotMatch(noonWorkbenchWorkspace, /aria-label="选择全部"/);
  assert.match(noonWorkbenchWorkspace, /暂无 SKU 数据/);
  assert.match(noonWorkbenchWorkspace, /点击下方按钮从 Noon Catalog 同步商品列表/);
  assert.match(noonWorkbenchWorkspace, /syncJobId/);
  assert.match(noonWorkbenchWorkspace, /fetch\(`\/api\/upload-jobs\/\$\{syncJobId\}`\)/);
  assert.match(noonWorkbenchWorkspace, /async function readSyncJobResponse\(response: Response\)/);
  assert.match(noonWorkbenchWorkspace, /if \(!response\.ok\) throw new Error/);
  assert.match(noonWorkbenchWorkspace, /同步任务响应缺少有效的 status/);
  assert.match(noonWorkbenchWorkspace, /response\.text\(\)/);
  assert.match(noonWorkbenchWorkspace, /JSON\.parse/);
  assert.match(noonWorkbenchWorkspace, /await readSyncJobResponse\(response\)/);
  assert.match(noonWorkbenchWorkspace, /noon-sync-progress/);
  assert.match(noonWorkbenchWorkspace, /noon-progress-track/);
  assert.match(noonWorkbenchWorkspace, /noon-sync-error/);
  assert.match(noonWorkbenchWorkspace, /parseSyncJobProgress/);
  assert.match(noonWorkbenchWorkspace, /已加载 \$\{result\.pagination\?\.totalItems \|\| result\.rows\?\.length \|\| 0\} 条 SKU 数据/);
  assert.match(noonWorkbenchWorkspace, /noon-sku-product-line/);
  assert.match(noonWorkbenchWorkspace, /noon-sku-header-line/);
  assert.match(noonWorkbenchWorkspace, /销售情况/);
  assert.match(noonWorkbenchWorkspace, /跟卖监控/);
  assert.match(noonWorkbenchWorkspace, /noon-sku-monitor/);
  assert.match(noonWorkbenchWorkspace, /MarketMetric/);
  assert.match(noonWorkbenchWorkspace, /MarketSource/);
  assert.match(noonWorkbenchWorkspace, /买家最终价/);
  assert.match(noonWorkbenchWorkspace, /OfferStatus/);
  assert.match(css, /\.noon-market-grid/);
  assert.match(css, /\.noon-sku-table[\s\S]*border-radius: var\(--radius\)/);
  assert.match(css, /\.noon-sku-product-line[\s\S]*font-family: var\(--font-ui\)/);
  assert.doesNotMatch(css, /\.noon-sku-(?:header-line|product-line)[\s\S]*min-width:\s*calc/);
  assert.match(css, /\.noon-sku-header-line[\s\S]*grid-template-columns: var\(--noon-check-col\)/);
  assert.match(css, /\.noon-sku-product-line[\s\S]*width: 100%/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*?\.noon-sync-card \{[\s\S]*?align-items: stretch;[\s\S]*?flex-direction: column;/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.shell \{[\s\S]*grid-template-columns: 1fr;/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.noon-catalog-hero \{[\s\S]*min-width: 0;/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.repository-workspace \{[\s\S]*grid-template-columns: minmax\(0, 1fr\);/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.product-bulk-bar \{[\s\S]*grid-template-columns: minmax\(0, 1fr\);/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.product-bulk-bar \.repository-control-row:last-child \{[\s\S]*justify-content: flex-start;/);
  assert.match(css, /\.noon-sync-actions \{[\s\S]*display: flex;[\s\S]*gap: var\(--space-2\);/);
  assert.match(css, /\.noon-empty-sync \.noon-sync-actions \{[\s\S]*justify-content: center;/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.noon-sync-actions \{[\s\S]*flex-wrap: wrap;/);
  assert.match(detailPage, /readProductDetail/);
  assert.match(detailPage, /完整 Noon 属性/);
  assert.match(detailPage, /product_group/);
  assert.match(detailPage, /variants/);
  assert.match(repositoriesRoute, /listRepositorySummaries/);
  assert.match(productsRoute, /listRepositoryProducts/);
  assert.match(uploadJobsRoute, /startUploadJob/);
  assert.match(uploadJobsRoute, /listUploadJobs/);
  assert.match(uploadJobRoute, /getUploadJob/);
  assert.match(uploadCancelRoute, /cancelUploadJob/);
  assert.match(catalogSyncRoute, /startNoonCatalogSyncJob/);
  assert.match(bulkOperationsRoute, /applyNoonWorkbenchBulkAction/);
  assert.match(bulkUpdatesRoute, /scripts\/export-noon-bulk-updates\.js/);
  assert.match(bulkUpdatesRoute, /global-product-update\.xlsx/);
  assert.match(bulkUpdateFilesRoute, /"exports", "noon-bulk-updates", "global"/);
  assert.match(productsLib, /readPlatformRepositories/);
  assert.match(productsLib, /readProductSummary/);
  assert.match(productsLib, /readProductDetail/);
  assert.match(productsLib, /normalizeNoonVariant/);
  assert.match(productsLib, /product_group_name_en/);
  assert.match(productsLib, /hsCode/);
  assert.match(jobsLib, /scripts\/upload-noon\.js/);
  assert.match(jobsLib, /collectRepositoryProductDirs/);
  assert.match(jobsLib, /scripts\/sync-noon-catalog-api\.js/);
  assert.match(jobsLib, /scripts\/sync-noon-catalog-internal-api\.js/);
  assert.match(jobsLib, /同步方案必须是 internal_api 或 export/);
  assert.match(jobsLib, /导出同步仅支持 Global 模式/);
  assert.match(jobsLib, /该店铺已有正在运行的目录同步任务/);
  assert.match(jobsLib, /source === "export" \? await findStoreSecret/);
  assert.match(jobsLib, /delete jobEnv\.NOON_API_TOKEN/);
  assert.match(catalogSyncRoute, /localAccessError\(request, \{ requireOrigin: true \}\)/);
  assert.match(uploadJobRoute, /localAccessError\(request\)/);
  assert.match(catalogSnapshotRoute, /localAccessError\(request\)/);
  assert.match(jobsLib, /startUploadJob/);
  assert.match(jobsLib, /startNoonCatalogSyncJob/);
  assert.match(jobsLib, /__noonToolsUploadJobs/);
});

test("next stores module has routes and dedicated management page", async () => {
  const home = await readFile(new URL("../src/app/page.tsx", import.meta.url), "utf8");
  const storesPage = await readFile(new URL("../src/app/stores/page.tsx", import.meta.url), "utf8");
  const workspace = await readFile(new URL("../src/app/stores/stores-workspace.tsx", import.meta.url), "utf8");
  const storesRoute = await readFile(new URL("../src/app/api/stores/route.ts", import.meta.url), "utf8");
  const storeRoute = await readFile(new URL("../src/app/api/stores/[id]/route.ts", import.meta.url), "utf8");
  const storeLoginRoute = await readFile(new URL("../src/app/api/stores/[id]/login/route.ts", import.meta.url), "utf8");
  const storeStatusRoute = await readFile(new URL("../src/app/api/stores/[id]/status/route.ts", import.meta.url), "utf8");
  const storesLib = await readFile(new URL("../src/lib/stores.ts", import.meta.url), "utf8");

  assert.match(home, /href="\/stores"/);
  assert.match(storesPage, /StoresWorkspace/);
  assert.match(workspace, /"use client"/);
  assert.match(workspace, /fetch\("\/api\/stores"\)/);
  assert.match(workspace, /apiToken/);
  assert.match(workspace, /hasApiToken/);
  assert.match(workspace, /tokenDialogStore/);
  assert.doesNotMatch(workspace, /window\.prompt/);
  assert.match(workspace, /storeSearch/);
  assert.match(workspace, /storeList/);
  assert.match(workspace, /addStoreButton/);
  assert.match(workspace, /storeDialog/);
  assert.match(workspace, /noonStatus/);
  assert.match(workspace, /checkNoonButton/);
  assert.match(workspace, /data-store-default/);
  assert.match(storesRoute, /listStores/);
  assert.match(storesRoute, /createStore/);
  assert.match(storeRoute, /deleteStore/);
  assert.match(storeRoute, /updateStore/);
  assert.match(storeLoginRoute, /startNoonStoreLoginJob/);
  assert.match(storeStatusRoute, /check-noon-status\.js/);
  assert.match(storesLib, /noonStoreUrl/);
  assert.match(storesLib, /defaultStoreId/);
  assert.match(storesLib, /findStoreSecret/);
  assert.match(storesLib, /apiToken/);
});

test("next collect module has job routes and reference controls", async () => {
  const home = await readFile(new URL("../src/app/page.tsx", import.meta.url), "utf8");
  const collectPage = await readFile(new URL("../src/app/collect/page.tsx", import.meta.url), "utf8");
  const workspace = await readFile(new URL("../src/app/collect/collect-workspace.tsx", import.meta.url), "utf8");
  const jobsRoute = await readFile(new URL("../src/app/api/jobs/route.ts", import.meta.url), "utf8");
  const jobRoute = await readFile(new URL("../src/app/api/jobs/[id]/route.ts", import.meta.url), "utf8");
  const cancelRoute = await readFile(new URL("../src/app/api/jobs/[id]/cancel/route.ts", import.meta.url), "utf8");
  const loginRoute = await readFile(new URL("../src/app/api/login-1688/route.ts", import.meta.url), "utf8");
  const jobsLib = await readFile(new URL("../src/lib/jobs.ts", import.meta.url), "utf8");

  assert.match(home, /href="\/collect"/);
  assert.match(collectPage, /CollectWorkspace/);
  assert.match(workspace, /"use client"/);
  for (const id of ["submitButton", "login1688Button", "collectStopButton", "clearCollectLogButton", "collectLog"]) {
    assert.match(workspace, new RegExp(`id="${id}"`));
  }
  assert.match(workspace, /fetch\("\/api\/jobs"/);
  assert.match(workspace, /fetch\("\/api\/login-1688"/);
  assert.match(workspace, /setInterval/);
  assert.match(jobsRoute, /startCollectJob/);
  assert.match(jobRoute, /getJob/);
  assert.match(cancelRoute, /cancelJob/);
  assert.match(loginRoute, /startLogin1688Job/);
  assert.match(jobsLib, /scripts\/collect-1688\.js/);
  assert.match(jobsLib, /scripts\/login-1688\.js/);
});
