import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const html = await readFile(new URL("../public/index.html", import.meta.url), "utf8");

test("product list renders directly on the repositories page and opens detail page", () => {
  assert.match(html, /class="product-page-shell"/);
  assert.match(html, /id="productPageRoot"/);
  assert.match(html, /function renderProductPage\(repositories,\s*options = \{\}\)/);
  assert.match(html, /data-page="product-detail"/);
  assert.match(html, /id="productDetailBody"/);
  assert.match(html, /function openProductDetailPage\(product\)/);
  assert.match(html, /openProductDetailPage\(product\)/);
  assert.match(html, /showRoute\("product-detail"\)/);
  assert.doesNotMatch(html, /openRepositoryDialog\(repository\)/);
  assert.doesNotMatch(html, /className = "repository-detail-panel"/);
  assert.doesNotMatch(html, /data-detail-panel/);
  assert.doesNotMatch(html, /class="variant-details"/);
  assert.doesNotMatch(html, /data-variant-details/);
});

test("repository detail uses grouped sku inspection tables", () => {
  assert.match(html, /class="variant-group-card"/);
  assert.match(html, />分组上传图片</);
  assert.match(html, /class="variant-group-table"/);
  assert.match(html, /function groupDetailVariants/);
  assert.doesNotMatch(html, />#\$\{index \+ 1\} ID</);
  assert.doesNotMatch(html, />Model</);
});

test("repository product UI follows the NoonMaster-style product workspace", () => {
  assert.match(html, /data-page="noon-workbench"/);
  assert.match(html, /id="noonWorkbenchRoot"/);
  assert.match(html, /className = "repository-summary-grid"/);
  assert.match(html, /className = "product-filter-panel"/);
  assert.match(html, /className = "product-search-panel"/);
  assert.match(html, /className = "product-command-panel"/);
  assert.match(html, /class="product-source-card"/);
  assert.match(html, /class="product-search-card"/);
  assert.match(html, /class="product-search-actions"/);
  assert.match(html, />搜索</);
  assert.match(html, /data-platform-source/);
  assert.match(html, /label:\s*"全部来源"/);
  assert.match(html, /label:\s*"Amazon"/);
  assert.match(html, /label:\s*"Noon"/);
  assert.match(html, /data-repository-source/);
  assert.match(html, />仓库数据源</);
  assert.doesNotMatch(html, /data-repository-tabs/);
  assert.doesNotMatch(html, /data-repository-id/);
  assert.match(html, /mode === "operations"/);
  assert.match(html, /className = "product-bulk-bar"/);
  assert.match(html, /className = "repository-controls repository-toolbar"/);
  assert.match(html, /data-set-price/);
  assert.match(html, /data-set-stock/);
  assert.match(html, /data-set-processing-time/);
  assert.match(html, /className = "repository-table-head"/);
  assert.match(html, /class="product-cover"/);
  assert.match(html, /class="product-title-button"/);
  assert.match(html, /productSourceId\(product\)/);
  assert.match(html, />1688 ID：/);
  assert.match(html, /class="product-health-dot"/);
  assert.match(html, /class="product-price"/);
  assert.match(html, /class="product-sku"/);
  assert.match(html, /class="product-upload-button"/);
  assert.match(html, /class="product-delete-button"/);
  assert.match(html, /class="detail-toolbar-actions"/);
  assert.match(html, /class="detail-product-layout"/);
  assert.match(html, /\.repository-table-head\s*\{[\s\S]*min-width:\s*1580px/);
});

test("repository controls keep compact consistent centered control styling", () => {
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] button,\s*\n\s*\.actions button,\s*\n\s*\.product-search-actions button,\s*\n\s*\.detail-toolbar-actions button,\s*\n\s*\.product-actions button,\s*\n\s*\.links button,\s*\n\s*\.bulk-export-links a,\s*\n\s*\.detail-links a,\s*\n\s*\.detail-links button,\s*\n\s*\.pager button,\s*\n\s*\.noon-mode-tabs button,\s*\n\s*\.product-pill,\s*\n\s*\.noon-chip\s*\{[\s\S]*display:\s*inline-flex/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] button,\s*\n\s*\.actions button,\s*\n\s*\.product-search-actions button,\s*\n\s*\.detail-toolbar-actions button,\s*\n\s*\.product-actions button,\s*\n\s*\.links button,\s*\n\s*\.bulk-export-links a,\s*\n\s*\.detail-links a,\s*\n\s*\.detail-links button,\s*\n\s*\.pager button,\s*\n\s*\.noon-mode-tabs button,\s*\n\s*\.product-pill,\s*\n\s*\.noon-chip\s*\{[\s\S]*align-items:\s*center/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] button,\s*\n\s*\.actions button,\s*\n\s*\.product-search-actions button,\s*\n\s*\.detail-toolbar-actions button,\s*\n\s*\.product-actions button,\s*\n\s*\.links button,\s*\n\s*\.bulk-export-links a,\s*\n\s*\.detail-links a,\s*\n\s*\.detail-links button,\s*\n\s*\.pager button,\s*\n\s*\.noon-mode-tabs button,\s*\n\s*\.product-pill,\s*\n\s*\.noon-chip\s*\{[\s\S]*justify-content:\s*center/);
  assert.doesNotMatch(html, /button:not\(\.quick-card\):not\(\.repository-tab\):not\(\.product-title-button\)/);
  assert.match(html, /input\[type="checkbox"\]\s*\{[^}]*width:\s*18px/);
  assert.match(html, /input\[type="checkbox"\]\s*\{[^}]*height:\s*18px/);
  assert.match(html, /\.product-row > input\[type="checkbox"\]\s*\{[^}]*width:\s*20px/);
  assert.match(html, /\.product-row > input\[type="checkbox"\]\s*\{[^}]*height:\s*20px/);
  assert.match(html, /\.pager button\.active\s*\{[^}]*width:\s*var\(--control-height\)/);
  assert.doesNotMatch(html, /\.pager button\.active\s*\{[^}]*width:\s*var\(--control-large\)/);
  assert.doesNotMatch(html, /\.product-row > input\[type="checkbox"\]\s*\{[^}]*width:\s*36px/);
});

test("navigation keeps a left aligned grid layout instead of centered action styling", () => {
  assert.match(html, /\.nav button\s*\{[^}]*display:\s*grid/);
  assert.match(html, /\.nav button\s*\{[^}]*grid-template-columns:\s*32px 1fr/);
  assert.match(html, /\.nav button\s*\{[^}]*align-items:\s*center/);
  assert.match(html, /\.nav button\s*\{[^}]*justify-content:\s*stretch/);
  assert.match(html, /\.nav button\s*\{[^}]*text-align:\s*left/);
});

test("bulk toolbar aligns selection text left and action buttons right", () => {
  assert.match(html, /\.repository-controls\s*\{[^}]*grid-template-columns:\s*minmax\(360px,\s*1fr\) auto/);
  assert.match(html, /\.repository-control-row\s*\{[^}]*align-items:\s*center/);
  assert.match(html, /\.repository-control-row\s*\{[^}]*gap:\s*10px/);
  assert.match(html, /\.repository-control-row \.meta\s*\{[^}]*display:\s*inline-flex/);
  assert.match(html, /\.repository-control-row \.meta\s*\{[^}]*align-items:\s*center/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\]\s*\{[^}]*justify-content:\s*end/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] \.actions\s*\{[^}]*align-items:\s*center/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] \.actions\s*\{[^}]*justify-content:\s*flex-start/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] \.actions\s*\{[^}]*max-width:\s*100%/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] \.actions\s*\{[^}]*margin-left:\s*auto/);
  assert.match(html, /\.repository-control-row\[data-bulk-actions\] \.actions\s*\{[^}]*padding-bottom:\s*0/);
  assert.doesNotMatch(html, /\.repository-control-row\s*\{[^}]*align-items:\s*end/);
});

test("noon listing operations live on a separate workbench", () => {
  assert.match(html, /data-route="noon-workbench"/);
  assert.match(html, />Noon 工作台</);
  assert.match(html, /id="noonWorkbenchRoot"/);
  assert.match(html, /class="panel pad product-job-panel"/);
  assert.match(html, /renderProductPage\(repositories,\s*\{\s*rootEl:\s*noonWorkbenchEl,\s*mode:\s*"operations"\s*\}\)/);
  assert.match(html, /className = "noon-catalog-hero"/);
  assert.match(html, />商品目录</);
  assert.match(html, />FBN\/FBP 模式</);
  assert.match(html, />Global \(NGS\) 模式</);
  assert.match(html, />重新同步</);
  assert.doesNotMatch(html, /data-catalog-detail/);
  assert.doesNotMatch(html, /openNoonCatalogDetailPage\(product\)/);
  assert.doesNotMatch(html, /function openNoonCatalogDetailPage\(row\)/);
  assert.match(html, /let noonCatalogMode = "global"/);
  assert.match(html, /data-noon-catalog-mode="fbn"/);
  assert.match(html, /data-noon-catalog-mode="global"/);
  assert.match(html, /function startNoonCatalogSync\(mode = noonCatalogMode\)/);
  assert.match(html, /\/api\/noon-catalog-sync-jobs/);
  assert.match(html, /\/api\/noon-catalog-sync\?\$\{syncParams\}/);
  assert.match(html, /function parseNoonCatalogLogLine\(line\)/);
  assert.match(html, /JSON\.parse\(line\)/);
  assert.match(html, />获取数据失败：/);
  assert.match(html, /button\.addEventListener\("click", \(\) => startNoonCatalogSync\(noonCatalogMode\)\)/);
  assert.doesNotMatch(html, /data-sync-sku\]"\)\.forEach\(\(button\) => \{\s*button\.addEventListener\("click", refreshProducts\)/);
  assert.match(html, /const catalogRows = isOperations && lastNoonCatalogSync\.mode === noonCatalogMode/);
  assert.match(html, /const hasSyncedNoonSkus = catalogRows\.length > 0/);
  assert.match(html, /const tableProducts = isOperations \? catalogRows : products/);
  assert.doesNotMatch(html, /const tableProducts = isOperations \? syncedProducts : products/);
  assert.match(html, /function parseNoonCatalogDetails\(text\)/);
  assert.match(html, /function noonCatalogRowCells\(row\)/);
  assert.match(html, /function normalizeNoonCatalogImageUrl\(value\)/);
  assert.match(html, /url\.searchParams\.get\("url"\)/);
  assert.match(html, /row\?\.imageUrl/);
  assert.match(html, /<img class="product-cover" src="\$\{escapeHtml\(imageUrl\)\}"/);
  assert.match(html, /const pskuMatch = value\.match/);
  assert.match(html, /const skuMatch = value\.match/);
  assert.match(html, /<h4 class="noon-product-title">/);
  assert.match(html, /<b>PSKU:<\/b>/);
  assert.match(html, /<b>SKU:<\/b>/);
  assert.match(html, /function renderNoonMetricCard\(market, label, value/);
  assert.match(html, /function renderPager\(\{ currentPage, totalPages, totalItems, pageSize \}\)/);
  assert.match(html, /class="pager-total">共 \$\{escapeHtml\(totalItems\)\} 条/);
  assert.match(html, /data-page-size aria-label="每页条数"/);
  assert.match(html, /data-page-jump inputmode="numeric"/);
  assert.match(html, /let pageSize = isOperations \? 10 : \(pagination\.pageSize \|\| 20\)/);
  assert.match(html, /line\.includes\("正在同步第"\)/);
  assert.match(html, /line\.match\(\/正在同步第\\s\+\(\\d\+\)/);
  assert.match(html, />买家最终价</);
  assert.match(html, />未关联 Noon 大师货源</);
  assert.match(html, />暂无 SKU 数据</);
  assert.match(html, />点击下方按钮从 Noon Catalog 同步商品列表</);
  assert.doesNotMatch(html, /class="product-source-card noon-filter-strip"/);
  assert.doesNotMatch(html, />状态：下线优先</);
  assert.doesNotMatch(html, />已筛选</);
  assert.match(html, />跟卖监控配额</);
  assert.match(html, />商品信息 <i class="sort-mark"><\/i></);
  assert.match(html, />售价 <i class="sort-mark"><\/i></);
  assert.match(html, />库存 <i class="sort-mark"><\/i></);
  assert.match(html, />销售情况 <i class="sort-mark"><\/i></);
  assert.match(html, />利润\/规格</);
  assert.match(html, />跟卖监控</);
  assert.match(html, />批量改商品属性</);
  assert.match(html, />批量调价</);
  assert.match(html, />批量改FBP\/NGS库存</);
  assert.match(html, />批量改时效</);
  assert.match(html, />导出 Global 表</);
  assert.match(html, />取消选择</);

  const repositoriesPage = html.match(/<section class="page" data-page="repositories">([\s\S]*?)<\/section>\s*<section class="page" data-page="noon-workbench">/);
  assert.ok(repositoriesPage, "repositories page should be before noon workbench");
  assert.match(repositoriesPage[1], /noon 上传作业/);
  assert.match(repositoriesPage[1], /id="uploadStoreId"/);

  const workbenchPage = html.match(/<section class="page" data-page="noon-workbench">([\s\S]*?)<\/section>\s*<section class="page" data-page="product-detail">/);
  assert.ok(workbenchPage, "noon workbench page should be before detail page");
  assert.doesNotMatch(workbenchPage[1], /noon 上传作业/);
  assert.doesNotMatch(workbenchPage[1], /id="uploadStoreId"/);
  assert.match(html, /mode === "upload"/);
  assert.match(html, /mode === "operations"/);
});

test("product detail page follows the reference information structure", () => {
  assert.match(html, /class="detail-product-layout"/);
  assert.match(html, /class="detail-page-toolbar"/);
  assert.match(html, />AI自动生成产品信息</);
  assert.match(html, />多分组上架</);
  assert.match(html, /class="detail-section-card"/);
  assert.match(html, /class="detail-product-editor"/);
  assert.match(html, />商品信息</);
  assert.match(html, />\* 商品标题 \(英文\)</);
  assert.match(html, />品类</);
  assert.match(html, />\* 品牌</);
  assert.match(html, />人群</);
  assert.match(html, />\* 商品状况</);
  assert.match(html, />卖点特征</);
  assert.match(html, />商品描述</);
  assert.match(html, />上架设置</);
  assert.match(html, />商品图片/);
  assert.match(html, />SKU 变体详情</);
  assert.match(html, /class="detail-image-grid"/);
  assert.match(html, /class="variant-group-table"/);
  assert.match(html, /const bullets = detailBullets\(group,\s*variants\)/);
  assert.match(html, /const description = detailFieldValue\(\[group,\s*\.\.\.variants\]/);
  assert.match(html, /description_en:\s*variant\.description_en/);
  assert.match(html, /feature_bullets_en:\s*variant\.feature_bullets_en/);
  assert.match(html, /\$\{renderVariantDetails\(variants\)\}/);
  assert.match(html, />物流 & 海关信息</);
  assert.match(html, /function renderProductDetailPage\(product,\s*detail\)/);
  assert.match(html, /function loadProductDetailData\(product\)/);
  assert.match(html, /function renderDetailProductContent\(product,\s*group,\s*variants\)/);
  assert.doesNotMatch(html, /summaryVariants\.length \|\| !product\.noonUrl/);
  assert.doesNotMatch(html, /class="detail-hero"/);
  assert.doesNotMatch(html, /class="detail-status-strip"/);
});

test("repository list leaves weight and dimensions to the detail page", () => {
  assert.match(html, /function productLogisticsText\(product\)/);
  assert.match(html, /return "详情查看"/);
  assert.doesNotMatch(html, /return `重量: \$\{weight\}\\n体积: \$\{size\}`/);
});
